import React, { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import "./style.css";

const API = import.meta.env.VITE_API_URL || (import.meta.env.PROD ? "" : "http://127.0.0.1:8000");
const formatTime = (value) => new Date(value).toLocaleTimeString("fr-FR", {hour:"2-digit", minute:"2-digit"});
const formatDate = (value) => new Date(value).toLocaleDateString("fr-FR", {day:"2-digit", month:"short"}); const formatToday = () => new Date().toLocaleDateString("fr-FR", {weekday:"long", day:"numeric", month:"long", year:"numeric"}).toUpperCase();
const days = ["Lun","Mar","Mer","Jeu","Ven","Sam","Dim"];
const spaceLabels = {dashboard:"Vue d’ensemble",calendar:"Calendrier",courses:"Mes cours",tutor:"Tuteur IA",checklist:"Objectifs",profile:"Mon profil",memory:"Mémoire de JARVIS",resources:"Mes ressources",settings:"Paramètres"};
const displayUrl = (url) => { let clean = url.replace("https://","").replace("http://",""); return clean.endsWith("/") ? clean.slice(0,-1) : clean; };
const defaultResources = [
  {id:"drive",title:"Google Drive",url:"https://drive.google.com/",category:"Organisation",fixed:true},
  {id:"github",title:"GitHub · JARVIS",url:"https://github.com/ninja959999/jarvis-scolaire",category:"Projet",fixed:true},
  {id:"vercel",title:"Vercel",url:"https://vercel.com/",category:"Déploiement",fixed:true},
  {id:"supabase",title:"Supabase",url:"https://supabase.com/",category:"Données",fixed:true},
  {id:"openrouter",title:"OpenRouter",url:"https://openrouter.ai/",category:"IA",fixed:true},
  {id:"sncf",title:"API SNCF",url:"https://numerique.sncf.com/startup/api/token-developpeur/",category:"Transport",fixed:true},
  {id:"pronote",title:"Pronote",url:"https://0280036m.index-education.net/pronote/eleve.html",category:"École",fixed:true}
];


function Icon({name,size=19}) {
  const paths = {
    grid:"M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM14 14h6v6h-6z",
    calendar:"M5 4v3M19 4v3M4 9h16M6 5h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2Z",
    book:"M4 5.5A2.5 2.5 0 0 1 6.5 3H20v16H6.5A2.5 2.5 0 0 0 4 21.5v-16ZM4 5.5v16M8 7h8M8 11h7",
    chat:"M20 11.5a7.5 7.5 0 0 1-8 7.5 8.5 8.5 0 0 1-4-.9L4 20l1.4-3.4A7.3 7.3 0 0 1 4 12a7.5 7.5 0 1 1 16 .5Z",
    check:"m5 12 4 4L19 6",
    bell:"M18 9a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9ZM10 22h4",
    plus:"M12 5v14M5 12h14",
    send:"m21 3-7.2 18-3.8-8-8-3.8L21 3ZM10 13l4-4",
    spark:"m12 3 1.7 5.3L19 10l-5.3 1.7L12 17l-1.7-5.3L5 10l5.3-1.7L12 3ZM19 16l.7 2.3L22 19l-2.3.7L19 22l-.7-2.3L16 19l2.3-.7L19 16Z",
    menu:"M4 6h16M4 12h16M4 18h16",
    arrow:"m9 18 6-6-6-6",
    sun:"M12 3v2M12 19v2M3 12h2M19 12h2M5.6 5.6 7 7M17 17l1.4 1.4M5.6 18.4 7 17M17 7l1.4-1.4M16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0Z",settings:"M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8ZM4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M3 12h2M19 12h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4M12 3v2M12 19v2"
  };
  return <svg className="icon" width={size} height={size} viewBox="0 0 24 24" fill={name==="grid"?"currentColor":"none"} stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name] && (name==="grid" ? <path d={paths[name]} /> : <path d={paths[name]} />)}</svg>;
}

function Card({title,icon,action,children,className=""}) {
  return <section className={`card ${className}`}><div className="card-head"><div className="title-wrap">{icon && <span className="title-icon"><Icon name={icon} size={17}/></span>}<h2>{title}</h2></div>{action}</div>{children}</section>;
}

function App() {
  const [data,setData]=useState(null); const [log,setLog]=useState(null); const [weather,setWeather]=useState(null); const [activeSpace,setActiveSpace]=useState("dashboard"); const [error,setError]=useState(""); const [showReminder,setShowReminder]=useState(false); const [saving,setSaving]=useState(false); const [mobileNav,setMobileNav]=useState(false); const [message,setMessage]=useState(""); const [aiLoading,setAiLoading]=useState(false); const [aiCanAct,setAiCanAct]=useState(()=>localStorage.getItem("jarvis_ai_can_act")==="true"); const [notice,setNotice]=useState(""); const [messages,setMessages]=useState([{from:"ai",text:"Salut ! Je peux t’aider à organiser ta journée, préparer une révision ou t’expliquer un cours."}]); const [memories,setMemories]=useState([]); const [memoryText,setMemoryText]=useState(""); const [memoryCategory,setMemoryCategory]=useState("preference"); const [memoryImportance,setMemoryImportance]=useState(3); const [memorySaving,setMemorySaving]=useState(false); const [showLaunch,setShowLaunch]=useState(()=>localStorage.getItem("jarvis_seen_launch")!=="true"); const [resources,setResources]=useState(()=>{try{const saved=JSON.parse(localStorage.getItem("jarvis_resources")||"null");return Array.isArray(saved)&&saved.length?saved:defaultResources}catch(e){return defaultResources}}); const [resourceTitle,setResourceTitle]=useState(""); const [resourceUrl,setResourceUrl]=useState(""); const [resourceCategory,setResourceCategory]=useState("Projet"); const [resourceSaving,setResourceSaving]=useState(false);
  const load=async()=>{try{setError("");const [d,l,w]=await Promise.all([fetch(`${API}/api/dashboard`),fetch(`${API}/api/logs/today`),fetch(`${API}/api/weather`)]);if(!d.ok||!l.ok)throw Error();setData(await d.json());setLog(await l.json());setWeather(w.ok?await w.json():null)}catch(e){setError("L’API n’est pas disponible pour le moment.")}};
  useEffect(()=>{load()},[]); useEffect(()=>{if(activeSpace==="memory")loadMemories()},[activeSpace]); useEffect(()=>{localStorage.setItem("jarvis_ai_can_act",String(aiCanAct))},[aiCanAct]); useEffect(()=>{localStorage.setItem("jarvis_resources",JSON.stringify(resources))},[resources]);
  const complete=async(kind,id)=>{await fetch(`${API}/api/${kind}/${id}/complete`,{method:"PATCH"});load()};
  const toggleLog=async(field)=>{const next={...log,[field]:!log[field]};setLog(next);await fetch(`${API}/api/logs/today`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({[field]:next[field]})})};
  const addReminder=async(e)=>{e.preventDefault();setSaving(true);const form=new FormData(e.currentTarget);const response=await fetch(`${API}/api/reminders`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:form.get("title"),trigger_time:new Date(form.get("trigger_time")).toISOString(),category:form.get("category")})});setSaving(false);if(!response.ok){setError("Impossible de créer le rappel.");return}setShowReminder(false);e.currentTarget.reset();load()};
  const addResource=async(e)=>{e.preventDefault();if(!resourceTitle.trim()||!resourceUrl.trim()||resourceSaving)return;setResourceSaving(true);let url=resourceUrl.trim();if(!url.startsWith("http://")&&!url.startsWith("https://"))url="https://"+url;try{new URL(url)}catch(err){notify("Entre une adresse web valide");setResourceSaving(false);return}setResources(v=>[{id:"custom-"+Date.now(),title:resourceTitle.trim(),url,category:resourceCategory,fixed:false},...v]);setResourceTitle("");setResourceUrl("");setResourceSaving(false);notify("Site ajouté à tes ressources")}; const removeResource=(id)=>{setResources(v=>v.filter(item=>item.id!==id));notify("Ressource retirée")}; const loadMemories=async()=>{try{const response=await fetch(`${API}/api/memories`);if(response.ok)setMemories(await response.json())}catch(e){notify("Mémoire indisponible pour le moment")}}; const saveMemory=async(e)=>{e.preventDefault();if(!memoryText.trim()||memorySaving)return;setMemorySaving(true);const response=await fetch(`${API}/api/memories`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({content:memoryText.trim(),category:memoryCategory,importance:Number(memoryImportance)})});setMemorySaving(false);if(!response.ok){notify("Impossible d’enregistrer ce souvenir");return}setMemoryText("");notify("Souvenir enregistré");loadMemories()}; const forgetMemory=async(id)=>{const response=await fetch(`${API}/api/memories/${id}`,{method:"DELETE"});if(response.ok){setMemories(v=>v.filter(item=>item.id!==id));notify("Souvenir oublié")}};  const notify=(text)=>{setNotice(text);setTimeout(()=>setNotice(""),2600)}; const goTo=(id,text)=>{document.getElementById(id)?.scrollIntoView({behavior:"smooth",block:"start"});notify(text);setMobileNav(false)}; const sendMessage=async(e)=>{
    e.preventDefault();
    const text=message.trim();
    if(!text||aiLoading)return;
    const history=[...messages,{from:"user",text}];
    setMessages(history);
    setMessage("");
    setAiLoading(true);
    try {
      const response=await fetch(API+"/api/ai/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({messages:history.map(item=>({role:item.from==="ai"?"assistant":"user",content:item.text}))})});
      const result=await response.json();
      if(!response.ok) throw new Error(result.detail||"Erreur IA");
      setMessages(v=>[...v,{from:"ai",text:result.message}]);
    } catch(error) {
      setMessages(v=>[...v,{from:"ai",text:"Je n’arrive pas à répondre : "+(error.message||"erreur serveur")+". Réessaie dans un instant."}]);
    } finally {
      setAiLoading(false);
    }
  };
  const week=useMemo(()=>{const today=new Date();const todayKey=today.toDateString();const monday=new Date(today);const day=today.getDay()||7;monday.setDate(today.getDate()-day+1);return days.map((label,i)=>{const d=new Date(monday);d.setDate(monday.getDate()+i);return {label,date:d,isToday:d.toDateString()===todayKey}})},[]);
  if(error)return <main className="app-shell"><div className="error-screen"><div className="logo">J</div><h1>JARVIS est momentanément indisponible</h1><p>{error}</p><button className="primary" onClick={load}>Réessayer</button></div></main>;
  if(!data||!log)return <main className="app-shell"><div className="loading-screen"><div className="loading-orb"><Icon name="spark" size={25}/></div><p>JARVIS prépare ton espace…</p></div></main>;
  if(showLaunch)return <main className="app-shell"><div className="launch-screen"><div className="launch-grid"/><div className="launch-mark"><span>J</span><i/></div><p className="launch-eyebrow">JARVIS · CENTRE DE CONTRÔLE</p><h1>Ton quotidien, enfin<br/><em>réuni au même endroit.</em></h1><p className="launch-copy">Cours, projets, mémoire et décisions utiles. JARVIS prépare ton espace pour t’aider à avancer avec plus de clarté.</p><div className="launch-metrics"><span><strong>{data.homeworks.length}</strong><small>devoirs à suivre</small></span><span><strong>{data.timetable.length}</strong><small>cours aujourd’hui</small></span><span><strong>{resources.length}</strong><small>outils prêts</small></span></div><button className="launch-button" onClick={()=>{localStorage.setItem("jarvis_seen_launch","true");setShowLaunch(false)}}>Ouvrir mon espace <Icon name="arrow" size={16}/></button><p className="launch-note"><i/> Données synchronisées · JARVIS est prêt</p></div></main>;
  return <main className="app-shell">
    <aside className={`sidebar ${mobileNav?"open":""}`}><div className="brand"><div className="brand-mark">J</div><div><strong>JARVIS</strong><span>Ton copilote scolaire</span></div><button className="mobile-close" onClick={()=>setMobileNav(false)}>×</button></div><nav><span className="nav-label">ESPACE DE TRAVAIL</span><button className={`nav-item ${activeSpace==="dashboard"?"active":""}`} onClick={()=>{setActiveSpace("dashboard");setMobileNav(false)}}><Icon name="grid"/>Vue d’ensemble</button><button className="nav-item" onClick={()=>{setActiveSpace("calendar");setMobileNav(false)}}><Icon name="calendar"/>Calendrier<span className="nav-badge">{data.timetable.length}</span></button><button className="nav-item" onClick={()=>{setActiveSpace("courses");setMobileNav(false)}}><Icon name="book"/>Mes cours</button><button className="nav-item" onClick={()=>{setActiveSpace("tutor");setMobileNav(false)}}><Icon name="chat"/>Tuteur IA</button><span className="nav-label second">SUIVI</span><button className="nav-item" onClick={()=>{setActiveSpace("checklist");setMobileNav(false)}}><Icon name="check"/>Objectifs</button><button className="nav-item" onClick={()=>notify("Aucune nouvelle notification")}><Icon name="bell"/>Notifications</button><button className={`nav-item ${activeSpace==="profile"?"active":""}`} onClick={()=>{setActiveSpace("profile");setMobileNav(false)}}><span className="nav-profile-mark">T</span>Mon profil</button><button className={`nav-item ${activeSpace==="resources"?"active":""}`} onClick={()=>{setActiveSpace("resources");setMobileNav(false)}}><Icon name="book"/>Mes ressources</button><button className={`nav-item ${activeSpace==="settings"?"active":""}`} onClick={()=>{setActiveSpace("settings");setMobileNav(false)}}><Icon name="settings"/>Paramètres</button><button className={`nav-item ${activeSpace==="memory"?"active":""}`} onClick={()=>{setActiveSpace("memory");setMobileNav(false)}}><Icon name="spark"/>Mémoire de JARVIS</button></nav><div className="sidebar-bottom"><div className="focus-card"><span className="focus-icon"><Icon name="spark" size={16}/></span><strong>Garde le rythme</strong><small>Chaque petite étape compte.</small><div className="progress"><i style={{width:"68%"}}/></div><em>68% de ta journée</em></div><div className="profile"><div className="avatar">T</div><div><strong>{data.user.name}</strong><span>Élève · Première</span></div><span className="profile-dot"/></div></div></aside>
    {mobileNav&&<div className="sidebar-overlay" onClick={()=>setMobileNav(false)}/>}
    <div className="main-content"><header className="topbar"><button className="menu-button" onClick={()=>setMobileNav(true)}><Icon name="menu"/></button><div className="breadcrumb"><span>Mon espace</span><Icon name="arrow" size={14}/><strong>{activeSpace==="dashboard"?"Vue d’ensemble":activeSpace==="calendar"?"Calendrier":activeSpace==="courses"?"Mes cours":activeSpace==="tutor"?"Tuteur IA":spaceLabels[activeSpace] || "Objectifs"}</strong></div><div className="top-actions"><button className="icon-button notification" onClick={()=>notify("Aucune nouvelle notification")}><Icon name="bell"/><i/></button><button className="avatar top-avatar" onClick={()=>setActiveSpace("profile")} aria-label="Ouvrir le profil">T</button></div></header>
      <div className="content">{activeSpace==="dashboard" && <><div className="welcome-row"><div><p className="overline">{formatToday()}</p><h1>Bonjour, {data.user.name} <span className="wave">✦</span></h1><p className="subtitle">Voici ce qui mérite ton attention aujourd’hui.</p></div><button className="refresh-button" onClick={load}><Icon name="sun" size={17}/> Actualiser</button></div>
      <section className="hero"><div className="hero-copy"><span className="hero-kicker"><Icon name="spark" size={14}/> BRIEFING DU JOUR</span><h2>On garde le cap.</h2><p>{data.homeworks.length} devoir{data.homeworks.length>1?"s":""} à traiter et {data.timetable.length} cours prévus aujourd’hui.{weather&&<> Il fait {Math.round(weather.temperature)}°C à {weather.city}.</>}</p><div className="hero-chips"><span><Icon name="check" size={14}/> Journée en cours</span><span><Icon name="calendar" size={14}/> Objectif : régularité</span>{weather&&<span><Icon name="sun" size={14}/> {weather.city} · {Math.round(weather.temperature)}°C</span>}</div></div><div className="hero-art"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="hero-sun"><Icon name="sun" size={35}/></div></div></section>
      <div className="stats-row"><div className="stat-card"><span className="stat-icon blue"><Icon name="book"/></span><div><small>DEVOIRS À FAIRE</small><strong>{data.homeworks.length}</strong><em>À traiter cette semaine</em></div></div><div className="stat-card"><span className="stat-icon purple"><Icon name="calendar"/></span><div><small>COURS AUJOURD’HUI</small><strong>{data.timetable.length}</strong><em>Dans ton emploi du temps</em></div></div><div className="stat-card"><span className="stat-icon green"><Icon name="check"/></span><div><small>PROGRESSION</small><strong>68%</strong><em>+12% cette semaine</em></div></div></div></>}
      {activeSpace !== "dashboard" && <section className="workspace-panel card">
        <div className="workspace-panel-head"><div><p className="overline">ESPACE DÉTAILLÉ</p><h2>{activeSpace==="calendar"?"Calendrier complet":activeSpace==="courses"?"Mes cours et devoirs":activeSpace==="tutor"?"Tuteur IA":activeSpace==="profile"?"Mon profil":activeSpace==="memory"?"Mémoire de JARVIS":activeSpace==="resources"?"Mes ressources":activeSpace==="settings"?"Paramètres":"Objectifs du jour"}</h2><p className="subtitle">{activeSpace==="calendar"?"Retrouve ici tous tes cours, horaires et salles.":activeSpace==="courses"?"Une vue claire de ce que tu dois faire et réviser.":activeSpace==="tutor"?"Pose une question et construis ta réponse avec JARVIS.":activeSpace==="profile"?"Gère tes connexions et les services utilisés par JARVIS.":activeSpace==="memory"?"Contrôle ce que JARVIS retient pour mieux t’aider.":activeSpace==="resources"?"Garde ici les sites dont tu as besoin pour tes projets.":activeSpace==="settings"?"Retrouve toutes les applications branchées ou prévues pour JARVIS.":"Suis tes petites habitudes et valide ta journée."}</p></div><button className="outline-button" onClick={()=>setActiveSpace("dashboard")}><Icon name="arrow" size={14}/> Retour à l’accueil</button></div>
        {activeSpace==="calendar" && <div className="detail-list">{week.map((d,i)=><div className="detail-day" key={d.label}><div className="detail-date"><strong>{d.date.getDate()}</strong><span>{d.label}</span></div><div>{d.isToday && data.timetable.length ? data.timetable.map(x=><div className="detail-event" key={x.id}><b>{formatTime(x.start_time)}</b><span><strong>{x.subject}</strong><small>{x.room||"Salle à confirmer"}</small></span></div>) : <p className="muted">{d.isToday?"Aucun cours prévu aujourd’hui.":"Aucun cours synchronisé pour ce jour."}</p>}</div></div>)}</div>}
        {activeSpace==="courses" && <div className="detail-list">{data.homeworks.length ? data.homeworks.map(x=><div className="detail-homework" key={x.id}><input type="checkbox" onChange={()=>complete("homeworks",x.id)}/><span><strong>{x.subject}</strong><small>{x.description}</small></span><em>À rendre le {formatDate(x.due_date)}</em></div>) : <p className="muted">Aucun devoir à traiter 🎉</p>}</div>}
        {activeSpace==="tutor" && <div className="detail-tutor"><div className="ai-orb"><Icon name="spark" size={32}/></div><div className="detail-chat"><div className="chat-preview">{messages.map((m,i)=><div className={`bubble ${m.from}`} key={i}>{m.text}</div>)}{aiLoading&&<div className="ai-thinking"><i/><i/><i/> JARVIS réfléchit…</div>}</div><form className="chat-form" onSubmit={sendMessage}><input value={message} onChange={e=>setMessage(e.target.value)} placeholder={aiLoading?"JARVIS réfléchit…":"Pose ta question à JARVIS…"} disabled={aiLoading}/><button aria-label="Envoyer" disabled={aiLoading}><Icon name="send" size={17}/></button></form></div></div>}
        {activeSpace==="profile" && <div className="profile-page"><div className="profile-identity"><div className="profile-avatar-large">T</div><div><h3>{data.user.name}</h3><p>{data.user.email}</p><span>Élève · Première</span></div></div><h3 className="section-label">CONNEXIONS</h3><div className="connection-grid"><div className="connection-card"><span className="connection-logo pronote">P</span><div><strong>Pronote</strong><small>Synchroniser cours, devoirs et notes</small></div><button className="outline-button" onClick={()=>notify("La connexion Pronote sera activée après la publication de ton espace")}>Connecter</button></div><div className="connection-card"><span className="connection-logo supabase">S</span><div><strong>Supabase</strong><small>Base de données JARVIS</small></div><span className="connection-status connected">Connecté</span></div><div className="connection-card"><span className="connection-logo openrouter">✦</span><div><strong>Tuteur IA</strong><small>OpenRouter · modèle gratuit</small></div><span className="connection-status connected">Connecté</span></div><div className="connection-card"><span className="connection-logo github">G</span><div><strong>GitHub</strong><small>Déploiement automatique</small></div><span className="connection-status connected">Connecté</span></div><div className="connection-card"><span className="connection-logo gcal">▣</span><div><strong>Google Calendar</strong><small>Importer et synchroniser ton agenda</small></div><button className="outline-button" onClick={()=>notify("Google Calendar sera connecté avec ton autorisation OAuth")}>Connecter</button></div><div className="connection-card"><span className="connection-logo gmail">@</span><div><strong>Gmail</strong><small>Lire uniquement les mails scolaires importants</small></div><button className="outline-button" onClick={()=>{window.location.href=`${API}/api/integrations/gmail/start`}}>Connecter</button></div></div><h3 className="section-label">AUTORISATIONS DE JARVIS</h3><label className="permission-row"><input type="checkbox" checked={aiCanAct} onChange={e=>setAiCanAct(e.target.checked)}/><span><strong>Autoriser JARVIS à agir dans mon espace</strong><small>Créer des rappels, gérer les tâches et préparer ta journée. Une confirmation sera toujours demandée avant une action.</small></span><Icon name="spark" size={17}/></label></div>}
        {activeSpace==="memory" && <div className="memory-page"><div className="memory-intro"><span className="ai-orb"><Icon name="spark" size={22}/></span><div><strong>Une mémoire sous ton contrôle</strong><p>JARVIS ne garde que ce que tu choisis d’enregistrer.</p></div></div><form className="memory-form" onSubmit={saveMemory}><input value={memoryText} onChange={e=>setMemoryText(e.target.value)} maxLength={1000} placeholder="Ex. Je préfère réviser les maths le soir..." /><select value={memoryCategory} onChange={e=>setMemoryCategory(e.target.value)}><option value="preference">Préférence</option><option value="objectif">Objectif</option><option value="scolaire">Scolaire</option><option value="habitude">Habitude</option></select><select value={memoryImportance} onChange={e=>setMemoryImportance(e.target.value)}><option value="1">Importance 1</option><option value="3">Importance 3</option><option value="5">Importance 5</option></select><button className="primary" disabled={memorySaving}>{memorySaving?"Enregistrement…":"Enregistrer"}</button></form><div className="memory-list">{memories.length?memories.map(item=><article className="memory-item" key={item.id}><div><span className="memory-category">{item.category}</span><p>{item.content}</p><small>Importance {item.importance}/5</small></div><button className="forget-button" onClick={()=>forgetMemory(item.id)}>Oublier</button></article>):<p className="muted">Aucun souvenir enregistré. Tu gardes le contrôle.</p>}</div></div>}
        {activeSpace==="settings" && <div className="settings-page"><div className="settings-banner"><span className="settings-glow"><Icon name="settings" size={23}/></span><div><strong>Les outils de ton écosystème</strong><p>Accède rapidement aux services utilisés par JARVIS. Les clés secrètes restent uniquement dans les variables du serveur.</p></div></div><div className="tool-grid">{[
          ["GitHub","Code source et déploiement","https://github.com/ninja959999/jarvis-scolaire","Connecté","github"],
          ["Vercel","Hébergement du frontend et de l’API","https://vercel.com/","Connecté","vercel"],
          ["Supabase","Base de données et mémoire","https://supabase.com/","Connecté","supabase"],
          ["OpenRouter","Modèle IA de JARVIS","https://openrouter.ai/","Connecté","openrouter"],
          ["Google Cloud","Identifiants OAuth Gmail / Google","https://console.cloud.google.com/apis/credentials","À vérifier","google"],
          ["Gmail","Lecture des mails importants","https://mail.google.com/","À connecter","gmail"],
          ["Pronote","Cours, devoirs et notes","https://0280036m.index-education.net/pronote/eleve.html","En attente du lycée","pronote"],
          ["SNCF API","Trajet La Loupe → Nogent-le-Rotrou","https://numerique.sncf.com/startup/api/token-developpeur/","Clé en attente","sncf"],
          ["Open-Meteo","Météo quotidienne","https://open-meteo.com/","Connecté","weather"]
        ].map(([title,description,url,status,kind])=><a className="tool-card" href={url} target="_blank" rel="noreferrer" key={title}><span className={"tool-logo "+kind}>{title.slice(0,1)}</span><span className="tool-copy"><strong>{title}</strong><small>{description}</small><em className={status==="Connecté"?"ok":""}>{status}</em></span><Icon name="arrow" size={16}/></a>)}</div></div>}
        {activeSpace==="resources" && <div className="resources-page"><div className="resource-form-wrap"><div><span className="section-label">NOUVEAU RACCOURCI</span><h3>Ajoute les sites de tes projets</h3><p>Un lien vers un cours, un dépôt, un outil ou une documentation : tout reste accessible depuis JARVIS.</p></div><form className="resource-form" onSubmit={addResource}><input value={resourceTitle} onChange={e=>setResourceTitle(e.target.value)} placeholder="Nom du site" maxLength={80} required/><input value={resourceUrl} onChange={e=>setResourceUrl(e.target.value)} placeholder="https://..." type="url" required/><select value={resourceCategory} onChange={e=>setResourceCategory(e.target.value)}><option>Projet</option><option>École</option><option>Organisation</option><option>Documentation</option><option>Autre</option></select><button className="primary" disabled={resourceSaving}>{resourceSaving?"Ajout…":"Ajouter le site"}</button></form></div><div className="resource-grid">{resources.map(item=><article className="resource-card" key={item.id}><a href={item.url} target="_blank" rel="noreferrer"><span className="resource-icon"><Icon name="arrow" size={17}/></span><span><strong>{item.title}</strong><small>{displayUrl(item.url)</small></span></a><div><em>{item.category}</em>{!item.fixed&&<button className="resource-delete" onClick={()=>removeResource(item.id)} aria-label={"Supprimer "+item.title}>×</button>}</div></article>)}</div></div>}
        {activeSpace==="checklist" && <div className="detail-list">{[["bag_prepared","Préparer le sac"],["clothes_prepared","Préparer les vêtements"],["sport_done","Séance de sport"]].map(([key,label])=><label className="detail-homework" key={key}><input type="checkbox" checked={!!log[key]} onChange={()=>toggleLog(key)}/><span><strong>{label}</strong><small>Une étape simple pour demain</small></span></label>)}</div>}
      </section>}
      <div className={`dashboard-grid ${activeSpace !== "dashboard" ? "is-hidden" : ""}`}><div id="calendar"><Card title="Calendrier de la semaine" icon="calendar" className="calendar-card" action={<button className="text-button" onClick={()=>setActiveSpace("calendar")} >Voir le calendrier <Icon name="arrow" size={14}/></button>}><div className="week-strip">{week.map((d,i)=><div className={`day ${d.isToday?"today":""}`} key={d.label}><span>{d.label}</span><strong>{d.date.getDate()}</strong></div>)}</div><div className="calendar-events">{data.timetable.length?data.timetable.map((x,i)=><div className={`event-row event-${i%3}`} key={x.id}><span className="event-time">{formatTime(x.start_time)}</span><span className="event-line"/><span className="event-info"><strong>{x.subject}</strong><small>{x.room||"Salle à confirmer"}</small></span>{x.is_cancelled&&<em>Annulé</em>}</div>):<p className="muted">Aucun cours prévu aujourd’hui.</p>}</div></Card></div>
      <div id="priorities"><Card title="Priorités du jour" icon="check" className="priority-card" action={<span className="count">{data.homeworks.length}</span>}><div className="task-list">{data.homeworks.length?data.homeworks.map(x=><label className="task" key={x.id}><input type="checkbox" onChange={()=>complete("homeworks",x.id)}/><span className="task-main"><strong>{x.subject}</strong><small>{x.description}</small></span><em>{formatDate(x.due_date)}</em></label>):<p className="muted">Tout est terminé 🎉</p>}</div><button className="outline-button" onClick={()=>setActiveSpace("courses")}>Voir mes devoirs <Icon name="arrow" size={14}/></button></Card></div>
      <div id="checklist"><Card title="Checklist du soir" icon="check" className="check-card"><div className="check-list"><label className="check-row"><input type="checkbox" checked={!!log.bag_prepared} onChange={()=>toggleLog("bag_prepared")}/><span><strong>Préparer le sac</strong><small>Pour démarrer sereinement</small></span><Icon name="check" size={16}/></label><label className="check-row"><input type="checkbox" checked={!!log.clothes_prepared} onChange={()=>toggleLog("clothes_prepared")}/><span><strong>Préparer les vêtements</strong><small>Gagner du temps demain</small></span><Icon name="check" size={16}/></label><label className="check-row"><input type="checkbox" checked={!!log.sport_done} onChange={()=>toggleLog("sport_done")}/><span><strong>Séance de sport</strong><small>30 minutes pour toi</small></span><Icon name="check" size={16}/></label></div></Card></div>
      <div id="tutor"><Card title="Tuteur IA" icon="spark" className="ai-card"><div className="ai-heading"><div className="ai-orb"><Icon name="spark" size={22}/></div><div><strong>Une question sur tes cours ?</strong><small>Ton espace de réflexion</small></div><span className="online"><i/> En ligne</span></div><div className="chat-preview">{messages.slice(-2).map((m,i)=><div className={`bubble ${m.from}`} key={i}>{m.text}</div>)}{aiLoading&&<div className="ai-thinking"><i/><i/><i/> JARVIS réfléchit…</div>}</div><form className="chat-form" onSubmit={sendMessage}><input value={message} onChange={e=>setMessage(e.target.value)} placeholder={aiLoading?"JARVIS réfléchit…":"Demande à JARVIS…"} disabled={aiLoading} /><button aria-label="Envoyer" disabled={aiLoading}><Icon name="send" size={17}/></button></form></Card></div>
      <Card title="Rappels" icon="bell" className="reminder-card" action={<button className="add" onClick={()=>setShowReminder(true)}><Icon name="plus" size={17}/></button>}>{data.reminders.length?data.reminders.map(x=><label className="task" key={x.id}><input type="checkbox" onChange={()=>complete("reminders",x.id)}/><span className="task-main"><strong>{x.title}</strong><small>{formatTime(x.trigger_time)} · {x.category}</small></span></label>):<div className="empty-reminders"><div><Icon name="bell" size={20}/></div><p>Aucun rappel en attente.<br/><span>Ajoute une petite étape à ta journée.</span></p></div>}</Card></div>
      <footer>JARVIS <span>v0.3</span> · Ton espace personnel · <a href={`${API}/docs`} target="_blank">Documentation API</a></footer></div></div>
    {notice&&<div className="toast" role="status">{notice}</div>}{showReminder&&<div className="modal-backdrop" onClick={()=>setShowReminder(false)}><form className="modal card" onSubmit={addReminder} onClick={e=>e.stopPropagation()}><div className="card-head"><div className="title-wrap"><span className="title-icon"><Icon name="bell" size={17}/></span><h2>Nouveau rappel</h2></div><button type="button" className="add" onClick={()=>setShowReminder(false)}>×</button></div><label className="field">Titre<input name="title" required maxLength="255" placeholder="Ex. Réviser les maths"/></label><label className="field">Date et heure<input name="trigger_time" required type="datetime-local"/></label><label className="field">Catégorie<select name="category"><option>PERSO</option><option>ÉCOLE</option><option>SPORT</option></select></label><button className="primary" disabled={saving}>{saving?"Enregistrement…":"Ajouter le rappel"}</button></form></div>}
  </main>;
}
createRoot(document.getElementById("root")).render(<App/>);
