create table if not exists public.memories (
  id bigint generated by default as identity primary key,
  user_id integer not null references public.users(id) on delete cascade,
  content text not null,
  category varchar(40) not null default 'preference',
  importance integer not null default 3 check (importance between 1 and 5),
  expires_at timestamp,
  created_at timestamp not null default now(),
  updated_at timestamp not null default now()
);

create index if not exists memories_user_id_idx on public.memories(user_id);
create index if not exists memories_user_importance_idx on public.memories(user_id, importance desc, updated_at desc);

alter table public.memories enable row level security;
revoke all on table public.memories from anon, authenticated;