create table if not exists public.users (
  id integer generated by default as identity primary key,
  email varchar(255) not null unique,
  name varchar(120) not null default 'Toi'
);

create table if not exists public.homeworks (
  id integer generated by default as identity primary key,
  subject varchar(120) not null,
  description text not null,
  due_date timestamp not null,
  priority_score double precision not null default 0,
  is_completed boolean not null default false,
  user_id integer not null references public.users(id) on delete cascade
);

create table if not exists public.timetable (
  id integer generated by default as identity primary key,
  subject varchar(120) not null,
  room varchar(120) not null default '',
  start_time timestamp not null,
  end_time timestamp not null,
  is_cancelled boolean not null default false,
  user_id integer not null references public.users(id) on delete cascade
);

create table if not exists public.reminders (
  id integer generated by default as identity primary key,
  title varchar(255) not null,
  trigger_time timestamp not null,
  category varchar(40) not null default 'PERSO',
  recurrence_rule varchar(80),
  is_completed boolean not null default false,
  user_id integer not null references public.users(id) on delete cascade
);

create table if not exists public.daily_logs (
  date date primary key,
  bag_prepared boolean not null default false,
  clothes_prepared boolean not null default false,
  sport_done boolean not null default false,
  homeworks_completed_ratio double precision not null default 0,
  user_id integer not null references public.users(id) on delete cascade
);

create index if not exists homeworks_user_id_idx on public.homeworks(user_id);
create index if not exists timetable_user_id_idx on public.timetable(user_id);
create index if not exists reminders_user_id_idx on public.reminders(user_id);
create index if not exists daily_logs_user_id_idx on public.daily_logs(user_id);

alter table public.users enable row level security;
alter table public.homeworks enable row level security;
alter table public.timetable enable row level security;
alter table public.reminders enable row level security;
alter table public.daily_logs enable row level security;

